# Generated by Django 4.2.4 on 2023-09-25 08:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('خصوصی', 'private'), ('نیمه خصوصی', 'semiprivate'), ('عمومی', 'public')], default='public', max_length=60)),
                ('time', models.CharField(max_length=50)),
                ('session', models.IntegerField()),
                ('tuition', models.IntegerField()),
                ('off', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('selected', models.BooleanField()),
                ('capacity', models.IntegerField()),
                ('gender', models.CharField(choices=[('آقایان', 'men'), ('بانوان', 'women')], max_length=10)),
                ('start', models.DateField(blank=True, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Product.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='Product.sport'),
        ),
    ]
