# Generated by Django 4.2.4 on 2023-09-14 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('day', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('خصوصی', 'private'), ('نیمه خصوصی', 'semiprivate'), ('عمومی', 'public')], default='public', max_length=60)),
                ('time', models.CharField(max_length=20)),
                ('session', models.IntegerField()),
                ('tuition', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('selected', models.BooleanField()),
                ('capacity', models.IntegerField()),
                ('gender', models.CharField(choices=[('آقایان', 'men'), ('بانوان', 'women')], max_length=10)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2023, 9, 14, 12, 26, 37, 655450, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
