# Generated by Django 4.2.4 on 2023-09-15 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 5, 59, 50, 399020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
