# Generated by Django 4.2.4 on 2023-09-23 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_course_off_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='day',
        ),
        migrations.AlterField(
            model_name='course',
            name='start',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Product.course')),
            ],
        ),
    ]
