# Generated by Django 4.2.4 on 2023-09-29 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='Session',
            new_name='session',
        ),
    ]
