# Generated by Django 4.2.4 on 2023-09-15 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_course_datetime_alter_course_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
