# Generated by Django 4.2.4 on 2023-09-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_course_session_alter_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessions',
            old_name='sessions',
            new_name='session',
        ),
    ]
