# Generated by Django 4.2.4 on 2023-09-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_course_day_alter_course_start_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='off',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
