# Generated by Django 4.2.4 on 2023-09-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_rename_session_participants_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='days',
            old_name='day',
            new_name='session',
        ),
    ]
