# Generated by Django 4.2.4 on 2023-10-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_participants_course_alter_participants_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='start',
        ),
    ]
