# Generated by Django 4.2.4 on 2023-10-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_participants_created_alter_participants_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='price',
        ),
    ]
