# Generated by Django 4.2.4 on 2023-11-01 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_remove_days_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participants',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Product.days'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Product.sessions'),
        ),
    ]
