# Generated by Django 4.2.4 on 2023-11-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_participants_description_alter_participants_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Product.days'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Product.sessions'),
        ),
    ]
