# Generated by Django 4.2.4 on 2023-12-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_alter_participants_day_alter_participants_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='off',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tuition',
        ),
        migrations.AddField(
            model_name='days',
            name='off',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='days',
            name='tuition',
            field=models.IntegerField(default=695000),
            preserve_default=False,
        ),
    ]
