# Generated by Django 4.2.4 on 2023-12-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_remove_course_off_remove_course_tuition_days_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='reserved',
        ),
    ]
