# Generated by Django 4.2.4 on 2024-01-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_participants_authority_participants_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='startDay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
