# Generated by Django 4.2.4 on 2024-03-08 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0010_time_res_id'),
        ('Product', '0018_alter_participants_startday'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='endDay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_participants', to='Calendar.day'),
        ),
    ]
