# Generated by Django 4.2.4 on 2024-03-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_participants_endday'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='end',
            field=models.CharField(default='شنبه', max_length=10),
        ),
    ]
