# Generated by Django 4.2.4 on 2024-03-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_days_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='days',
            name='end',
        ),
    ]
