# Generated by Django 4.2.4 on 2023-10-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='num',
            new_name='number',
        ),
    ]
