# Generated by Django 4.2.4 on 2023-10-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_rename_num_day_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
