# Generated by Django 4.2.4 on 2023-10-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0004_alter_day_month_alter_month_year_alter_time_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='Calendar.month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='months', to='Calendar.year'),
        ),
    ]
