# Generated by Django 4.2.4 on 2023-10-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0006_alter_day_number_alter_month_number_alter_time_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='startDay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
