# Generated by Django 4.2.4 on 2023-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0007_month_startday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
