# Generated by Django 4.2.4 on 2023-10-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0008_alter_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='off',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='time',
            name='price',
            field=models.IntegerField(default=695000),
        ),
    ]
