# Generated by Django 4.2.4 on 2024-02-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0009_time_off_time_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='res_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
