# Generated by Django 4.2.4 on 2023-09-07 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 19, 12, 7, 810424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='slider',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 19, 12, 7, 809774, tzinfo=datetime.timezone.utc)),
        ),
    ]
