# Generated by Django 4.2.4 on 2023-09-14 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_article_datetime_slider_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 6, 53, 46, 454502, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 6, 53, 46, 454502, tzinfo=datetime.timezone.utc)),
        ),
    ]
