# Generated by Django 4.2.4 on 2023-09-14 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_article_datetime_alter_slider_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 7, 11, 41, 932989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 7, 11, 41, 931987, tzinfo=datetime.timezone.utc)),
        ),
    ]
