# Generated by Django 4.2.4 on 2023-09-14 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_alter_article_datetime_alter_slider_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 49, 21, 625133, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 14, 11, 49, 21, 624131, tzinfo=datetime.timezone.utc)),
        ),
    ]
