# Generated by Django 4.2.4 on 2023-09-15 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_alter_article_datetime_alter_slider_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 5, 59, 50, 398020, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='slider',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 5, 59, 50, 397020, tzinfo=datetime.timezone.utc)),
        ),
    ]
