# Generated by Django 4.2.4 on 2023-09-15 06:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_alter_article_datetime_alter_slider_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='slider',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
