# Generated by Django 4.2.4 on 2023-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=50, null=True, unique=True)),
                ('instagram', models.CharField(max_length=50, null=True, unique=True)),
                ('telephone', models.CharField(max_length=11, null=True, unique=True)),
                ('phone', models.CharField(max_length=13, null=True, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('transparent_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
