# Generated by Django 4.2.4 on 2023-09-28 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
