# Generated by Django 4.2.4 on 2023-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0002_alter_aboutus_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='location',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
