# Generated by Django 4.2.4 on 2023-10-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_accountid_alter_user_accountnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(blank=True, choices=[('آزاد', 'free'), ('درصدی', 'percentage'), ('ثابت', 'static')], max_length=20, null=True),
        ),
    ]
