# Generated by Django 4.2.4 on 2023-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(blank=True, choices=[('درصدی', 'percentage'), ('ثابت', 'static')], max_length=20, null=True),
        ),
    ]
