# Generated by Django 4.2.4 on 2023-12-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='debt',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='accountId',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='accountNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='user',
            name='situation',
            field=models.CharField(blank=True, choices=[('بدهکار', 'debt'), ('تسویه', 'clear')], max_length=20, null=True),
        ),
    ]
