# Generated by Django 4.2.4 on 2024-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_rename_telephone_user_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='situation',
            field=models.CharField(blank=True, choices=[('بدهکار', 'debt'), ('تسویه', 'clear'), ('پستانکار', 'mammal')], max_length=20, null=True),
        ),
    ]
