# Generated by Django 4.2.4 on 2024-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_user_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.CharField(blank=True, choices=[('درصدی', 'درصدی'), ('ثابت', 'ثابت')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='situation',
            field=models.CharField(blank=True, choices=[('بدهکار', 'بدهکار'), ('تسویه', 'تسویه'), ('پستانکار', 'پستانکار')], max_length=20, null=True),
        ),
    ]
