# Generated by Django 4.2.4 on 2023-10-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='reserved',
            new_name='holiday',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='endDateTime',
        ),
        migrations.AddField(
            model_name='reservations',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
