# Generated by Django 4.2.4 on 2023-10-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0003_rename_reserved_reservations_holiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='date',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='Times',
        ),
    ]
