# Generated by Django 4.2.4 on 2023-10-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_alter_reservations_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='duration',
        ),
    ]
