# Generated by Django 4.2.4 on 2023-10-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0008_alter_time_duration'),
        ('Reservation', '0006_remove_reservations_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='startDateTime',
        ),
        migrations.AddField(
            model_name='reservations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='Calendar.time'),
        ),
    ]
