# Generated by Django 4.2.4 on 2023-10-17 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0008_reservations_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
