# Generated by Django 4.2.4 on 2023-10-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0009_gym_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='off',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='tuition',
        ),
    ]
