# Generated by Django 4.2.4 on 2023-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0010_remove_gym_off_remove_gym_tuition'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
