# Generated by Django 4.2.4 on 2023-12-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0011_reservations_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='authority',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='success',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
