# Generated by Django 4.2.4 on 2024-01-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0014_reservations_enddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='endDate',
        ),
    ]
