# Generated by Django 4.2.4 on 2024-05-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0015_remove_reservations_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='endDate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
