# Generated by Django 4.2.4 on 2024-07-01 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0011_alter_month_name'),
        ('Seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='Calendar.day'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(choices=[('کنسلی', 'کنسلی'), ('تعطیل', 'تعطیل'), ('بقیه', 'بقیه')], default='public', max_length=100),
        ),
    ]
